### ISSUE TITLE
Create a Python 3.x Version

### ISSUE THREAD

**Issue by JasonBristol** [JasonBristol/pypicker#27]

**Comment by suresttexas00** [comment]
Sorry to interrupt the course of this thread over here...  I just wanted to clear up a few things and I can't really say them over there without creating hard feelings.
1) I am not really a "collaborator".  I am only a very involved user with a vested interest in improving wrapper.  Ben has given me NO authority to do approve PR's or really _do anything at all_.  I think he is making jokes about me being a "collaborator ... forever".
that is the main one I wanted to clear up.

I really appreciate what you have been doing; you are a skilled person who is obviously a more experienced programmer and I really appreciate your input and helping to get Ben moving on PR's.. IT IS VERY HARD to get him to pull anything at all!
I like the ideas you have proposed and I think they make sense.

We may need to propose to Ben that he create (or let us create) an "authorized" "3rd" branch, maybe called uberDevelopment or something for our "cutting edge" work.  Which brings me to problem #2 as I see it:
2) The copyright on "his code":
```THE FOLLOWING ONLY APPLIES TO ___HIS____ CODE:
DO NOT REDISTRIBUTE WITHOUT MY WRITTEN PERMISSION. DO NOT USE MY PARTS OF THE CODE WITHOUT MY WRITTEN PERMISSION.
MY (____HIM______) CODE MAY NOT BE REDISTRIBUTED TO THE PUBLIC FOR ANY PURPOSE, INCLUDING BUT NOT LIMITED TO COMMERCIAL USE. IT IS 
ONLY OPEN SOURCE FOR EDUCATIONAL PURPOSES. ```
I don't know if this is the reason for some of the way he handles everything... I wish it were open source, but it appears not.

I will delete this little note after you have read this.  If you wish to email or correspond directly, you can email SurestTexas00@live.com

**Comment by JasonBristol** [comment]
Pushed to v1.0 @e04ea84
